### ISSUE TITLE
The restart link does not work at all.

### ISSUE THREAD

**Issue by Syringegoogleplex** [hczhcz/Another-Flappy-2048#1]
When you lose, a link is supposed to come up, but instead, there is underlined text that does nothing.
![img_1750](https://cloud.githubusercontent.com/assets/27730166/26246472/46feac0c-3c91-11e7-9dbf-9927061e9642.PNG)
:rage4: :rage4: :rage4: :rage4: :rage4:

**Comment by Syringegoogleplex** [comment]
Bruh

**Comment by hczhcz** [comment]
Fixed. Thank you for adding this issue.
